routes/web.php
<?php

Artisan::call('view:clear');

// Auth
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/', 'Auth\LoginController@index')->name('main');

// News
// $router->resource('news', 'NewsController')->middleware('admin');
// Route::post('news/remove', 'NewsController@remove')->middleware('admin');
// Route::get('news/{news}/edit','NewsController@edit')->name('news.edit');

// Contacts
Route::post('contacts/remove', 'ContactController@remove')->middleware('admin');
$router->resource('contacts', 'ContactController')->middleware('admin');

// Streets
$router->resource('streets', 'StreetController')->middleware('admin');

// Buildings
$router->resource('buildings', 'BuildingController')->middleware('admin');
Route::post('buildings/remove', 'BuildingController@remove')->middleware('admin');

// Users
Route::get('users/balance', 'UsersController@getBalance')->middleware('auth', 'admin_user');
Route::get('users/street/{street}', 'UsersController@street')->middleware('admin');
Route::post('users/remove', 'UsersController@remove')->middleware('admin');
Route::post('users/phone', 'UsersController@handlerConfirmationPhone')->middleware('auth');
Route::post('users/phone-confirm', 'UsersController@confirmPhone')->middleware('auth');
Route::post('users/email', 'UsersController@handlerConfirmationEmail');
Route::get('users/email-confirm/{token}', 'UsersController@confirmEmail')->name('users.email-confirm');
Route::post('users/unbind', 'UsersController@unbind')->middleware('admin');
$router->resource('users', 'UsersController')->middleware('admin');

// Autos
// Route::post('autos/remove', 'AutoController@remove')->middleware('auth', 'admin_user');
// Route::post('autos/change', 'AutoController@change')->middleware('auth', 'admin_user');
// $router->resource('autos', 'AutoController')->middleware('auth', 'admin_user');

// Guests
// Route::post('guests/remove', 'GuestController@remove')->middleware('auth', 'admin_user');
// Route::post('guests/change', 'GuestController@change')->middleware('auth', 'admin_user');
// $router->resource('guests', 'GuestController')->middleware('auth', 'admin_user');

// Cars
Route::post('cars/remove', 'CarController@remove')->middleware('auth', 'admin_user');
Route::post('cars/change', 'CarController@change')->middleware('auth', 'admin_user');
$router->resource('cars', 'CarController')->middleware('auth', 'admin_user');

// Peoples
Route::post('peoples/remove', 'PeopleController@remove')->middleware('auth', 'admin_user');
Route::post('peoples/change', 'PeopleController@change')->middleware('auth', 'admin_user');
$router->resource('peoples', 'PeopleController')->middleware('auth', 'admin_user');

// Profiles
$router->resource('profiles', 'ProfileController')->middleware('auth', 'user');
Route::get('profiles', 'ProfileController@index')->name('profiles.index')->middleware('auth', 'user');
Route::post('kins/remove', 'ProfileController@remove')->middleware('auth', 'user');

// Indications (on home page icons electricity and water)
Route::get('indications/month/{month}', 'IndicationController@month')->middleware('admin');
Route::post('indications/{indication}', 'IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications', 'IndicationController')->middleware('admin');

// Information
Route::get('informations/{sys_id}', 'InformationController@index')->middleware('auth');

// Indications
Route::get('indications/month/{month}','IndicationController@month')->middleware('admin');
Route::post('indications/{indication}','IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications','IndicationController')->middleware('admin');

// Polls
$router->resource('polls', 'PollController')->middleware('admin');
Route::post('polls/insert', 'PollController@insert');

// Additionals
Route::post('additionals/store', 'AdditionalController@store')->name('additionals.store');
Route::post('additionals/pay', 'AdditionalController@pay')->name('additional_pay');
Route::get('additionals/pdf', 'AdditionalController@makePdfAct');
Route::post('additionals/pay-unpaid', 'AdditionalController@payUnpaid');
Route::get('additionals/list', 'AdditionalController@lists');
Route::post('additionals/send/act', 'AdditionalController@sendAct')->name('additionals_send_act');
$router->resource('additionals', 'AdditionalController');

Auth::routes();
Route::post('password/change', 'UsersController@changePassword')->middleware('user');

// Access
Route::get('permitions', 'PermitionController@index')->name('permitions')->middleware('auth', 'admin_user');
Route::get('permitions/list', 'PermitionController@list')->name('permitions_list')->middleware('auth', 'admin_security');
Route::get('permitions/list/check', 'PermitionController@check');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth', 'common');

// Invoices
Route::group(['prefix' => 'invoices', 'middleware' => 'auth', 'middleware' => 'user'], function() {
    Route::get('/', 'InvoiceController@index');
    Route::get('period', 'InvoiceController@getAllByPeriod');
    Route::get('pdf', 'InvoiceController@showInPdf');
});

// Crons
Route::group(['prefix' => 'crons'], function() {
    Route::post('payments/confirm', 'CronController@confirmPayments'); 
    Route::post('users/add-counteragent-key', 'CronController@addCounteragentKey');
    Route::post('payments/mark-unpaid', 'CronController@markUnpaidPayments');
    Route::post('receipt/email', 'CronController@sentEmailReceiptPdf');
    Route::post('receipt/reset', 'CronController@resetReceipt');
    Route::post('cars/delete-expired-permition', 'CronController@deleteCarsWithExpiredPermition');
    // Route::get('test', 'CronController@test');
});

// Payments
Route::group(['prefix' => 'payments'], function() {
    Route::post('/', 'PaymentController@store')->middleware('auth', 'user');
    Route::post('handler', 'PaymentController@handler');
    // метод для тестов разной хуйни
    Route::get('cashbox', 'PaymentController@cashbox')->middleware('auth', 'user');
});

$router->resource('receipt', 'ReceiptController');

// Logs
Route::get('logs', 'LogController@index')->name('logs')->middleware('auth', 'admin');

// Route::get('streets','StreetController@index')->name('streets.index');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'role',
        'name',
        'last_name',
        'first_name',
        'middle_name',
        'invoice_num',
        'email',
        'phone',
        'building_id',
        'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Auth\Events\PasswordReset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use App\Services\OneC\IOneC;
use App\Models\Balance\IBalance;
use App\Services\Sms\ISms;
use App\Models\Street;
use App\Models\Users;
use App\Models\Building;
use DB;

class UsersController extends Controller
{
    protected function validator(array $data)
    {
        $validator = Validator::make($data, [
            'last_name' => 'required|string|max:255',
            'first_name' => 'required|string|max:255',
            'middle_name' => 'required|string|max:255',
            'invoice_num' => 'integer',
        ]);

        return $validator;
    }

    protected function password_validator(array $data)
    {
        $validator = Validator::make($data, [
            'old_password' => 'required|string',
            'new_password' => 'required|string|min:6|confirmed',
        ]);

        return $validator;
    }

    public function index(Users $allUsers, Request $request)
    {
        if (!$request['street']) {
            $request['street'] = 1;
        }
        
        $users = $allUsers->getByStreet($request['street']);
        $streets = Street::all();
        $active_street = $request['street'];
        $buildings = Building::getFreeBuildings();

        return view('users.index', [
            'users' => $users,
            'streets' => $streets,
            'buildings' => $buildings,
            'active_street' => $active_street
        ]);
    }

    public function edit(Request $request, Users $singleUser)
    {
        $single = $singleUser->getUserForEdit($request->id);
        return json_encode($single);
    }

    public function changePassword(Request $request)
    {
        if (password_verify($request['old_password'], Auth::user()->password)) {
            $this->password_validator($request->all())->validate();
            Auth::user()->password = Hash::make($request['new_password']);
            Auth::user()->save();
            event(new PasswordReset(Auth::user()));
            $result = 'Пароль изменён!';
            return $result;
        } else {
            //Для того чтобы стандартные и сампоисные ошибки выводились одинаково, привожу к единому виду объект
            $errors = ['old_password' => [0 => 'Старый пароль введён не верно']];
            return response(json_encode(['errors' => $errors]), 400);
        }
    }

    public function handlerConfirmationPhone(Request $request, Users $userModel, ISms $smsService)
    {
        $confirmationCode = rand(1000, 9000);

        $confirmedPhones = $userModel->getConfirmedPhones();

        if ($this->isPhoneConfirmation($request->phone, $confirmedPhones)) {
            return response()->json([
                'message' => 'Bad Request',
                'overview' => 'Данный телефон уже подтверждён!'
            ], 400);
        } else {
            $content = urlencode("Код подтверждения: " . $confirmationCode);

            $userModel->createPhoneForConfirm($request, $confirmationCode);
            $smsService->sendSmsMessage($content, $request->phone);
        }
    }

    public function isPhoneConfirmation($currentPhone, $confirmedPhones)
    {   
        $phone = $confirmedPhones->whereIn('phone', $currentPhone);

        if ($phone->isNotEmpty()) {
            return true;
        }

        return false;
    }

    public function confirmPhone(Request $request, Users $usersModel)
    {
        $user = $usersModel->getUserPhoneCode(Auth::user()->id);

        if ((int) $request->confirmation_code == $user->confirmation_code) {
            $status = 1;
            return $usersModel->changeStatusPhone($request, $status);
        } else {
            return response()->json([
                'message' => 'Bad request',
                'overview' => 'Не правильный код подтверждения'
            ], 400);
        }
    }

    public function handlerConfirmationEmail(Request $request)
    {
        $url = route('users.email-confirm', [
            'token' => $request->token,
            'email' => $request->email
        ]);

        Mail::send('emails.confirm_email', array('url' => $url), function ($message) use ($request) {
            $message->to($request->email, $request->name)->subject('Подтверждение e-mail. Личный кабинет "Донской"');
        });
    }

    public function confirmEmail(Request $request, Users $usersModel)
    {
        $usersModel->where('id', '=', Auth::id())->update(['email' => $request->email]);
        return redirect()->route('profiles.index');
    }

    public function street(Users $userModel)
    {
        $streets = Street::all();

        $users = $userModel->getByStreet($_GET['street']);

        return view('users.list', [
            'streets' => $streets, 
            'users' => $users, 
            'street' => $_GET['street']
        ]);
    }

    public function update(Users $updateUser, Request $request)
    {
        $error = $this->validator($request->all())->validate();

        if ($error) {
            return $error;
        }

        $result = $updateUser->where('id', '=', $request->id)->update($request->except(['_token', '_method', 'street_id']));

        return $result;
    }

    public function remove(Users $removeUser)
    {
        return $removeUser->where('id','=',$_POST['id'])->update(['alive'=>false]);
    }

    /**
     * Unbind user the apartment
     */
    public function unbind(Request $request)
    {
        DB::beginTransaction();

        try {
            Users::where('id', $request->id)->update(['building_id' => NULL]);
            Building::where('user_id', $request->id)->update(['user_id' => NULL]);
        } catch (Exception $e) {
            DB::rollback();       
        }

        DB::commit();
        return 1;
    }

    public function getBalance(IBalance $balance, IOneC $one_c_service)
    {
        $balance = $balance->show(Auth::user()->invoice_num, $one_c_service);
        return json_encode($balance);
    }
}

resources/views/users/index.blade.php
@extends ('app')

@section ('content')
    <main class="uk-background-default uk-padding">
        <div class="uk-container uk-padding-remove uk-margin-top">
            <div class="uk-width-1-1 uk-text-lead uk-margin-bottom">Пользователи</div>
            <div class="" uk-grid>
                <div class="uk-width-1-3@m uk-width-1-1@s street-container">
                    <ul class="street-list uk-list">
                        {{--ВСТАВИТЬ УЛИЦЫ--}}
                        @foreach ($streets as $street)
                            <a href="{{ route("users.index",['street'=>$street->id]) }}">
                                <li class="street-list_item @if( isset($active_street) and $street->id == $active_street) active @endif"
                                    id="{{ $street->id }}" map_id="{{ $street->map_id }}">
                                    {{ $street->name }}
                                </li>
                            </a>
                        @endforeach
                    </ul>
                    <button class="button button-icon" data-mode="create">
                        <img src="img/icon/admin/plus.svg">Создать пользователя
                    </button>
                </div>

                <div class="uk-width-2-3@m uk-width-1-1@s uk-padding uk-padding-remove-top uk-padding-remove-right uk-overflow-auto table-container user_list">
                    {{--USER LIST--}}
                    <table class="uk-table uk-table-divider uk-table-hover table-border-left" table="users">
                        <thead class="table-header">
                        <th>Пользователь</th>
                        <th>Лиц.счёт</th>
                        <th>Телефон</th>
                        <th>Почтовый ящик</th>
                        <th></th>
                        </thead>
                        <tbody>
                        @foreach ($users as $user)
                            <tr class="table_item" id={{ $user->id }}>
                                <td>
                                    <div>{{ $user->last_name }} {{ $user->first_name }} {{ $user->middle_name }}</div>
                                    <div>ул.{{ $user->street_name }}, {{ $user->building_number }}
                                        @if ($user->apart_number)
                                            {{'кв. '}}{{ $user->apart_number }}
                                        @endif
                                    </div>
                                </td>
                                <td>
                                    {{ $user->invoice_num }}
                                </td>
                                <td>
                                    {{ $user->phones }}
                                </td>
                                <td>
                                    {{ $user->email }}
                                </td>
                                <td>
                                    <div class="button-group">
                                        <button class="button button-transparent button-icon" data-mode="edit"><img
                                                    src="img/icon/admin/street/edit.svg"></button>
                                        <button class="button button-transparent button-icon" data-mode="delete"><img
                                                    src="img/icon/admin/street/delete.svg"></button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $users->appends(['street'=>$active_street])->links() }}
                </div>
            </div>
        </div>
    </main>

    <form class="hidden-form uk-padding uk-flex uk-flex-column users-create_form" method="POST" title="Регистрация" action="{{ route('register') }}">
        {{ csrf_field() }}

        <div class="material-input">
            <label for="role" class="material-input_label">Роль пользователя</label>
            <select class="material-input_text" id="role" name="role" onchange="showLines(this.value)">
                <option value="1">Руководитель</option>
                <option selected value="4">Пользователь</option>
                {{--<option value="5">Работник</option>--}}
            </select>
        </div>
        <div class="material-input" data-block="auth_block">
            <label class="material-input_label" for="name">Логин</label>
            <input class="material-input_text" name="name" id="name" type="text" required autofocus/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="password">Пароль</label>
            <input class="material-input_text" name="password" id="password" type="password" pattern="^(\w+){3,32}$"
                   required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="password-confirm">Подтвердите пароль</label>
            <input class="material-input_text" id="password-confirm" type="password" name="password_confirmation"
                   required>
        </div>

        <div class="material-input">
            <label class="material-input_label" for="last_name">Фамилия</label>
            <input class="material-input_text" name="last_name" id="last_name" data-input="name" type="text" required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="first_name">Имя</label>
            <input class="material-input_text" name="first_name" id="first_name" data-input="name" type="text"
                   required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="middle_name">Отчество</label>
            <input class="material-input_text" name="middle_name" id="middle_name" data-input="name" type="text"
                   required/>
        </div>
        <div class="material-input" data-view="4">
            <label for="invoice_num" class="material-input_label">Лицевой счет</label>
            <input name="invoice_num" class="material-input_text" id="invoice_num"/>
        </div>

        <div class="material-input" data-view="4">
            <label for="building_id" class="material-input_label"></label>
            <select id="building_id" class="material-input_text" person="true" type="text" name="building_id">
                <option selected value="0">Свободные дома</option>

                @foreach ($buildings as $build)
                    <option value="{{ $build->id }}"> ул.{{ $build->street_name }}
                        {{ $build->building_number }}
                        @if ($build->apart_number)
                            {{ 'кв. ' }}{{ $build->apart_number }}
                        @endif
                    </option>
                    @endforeach
            </select>
        </div>
        <button class="button uk-margin-top" data-action="register" type="submit">Записать</button>

    </form>

    <form action="{{ route('users.store') }}" class='hidden-form uk-padding uk-flex uk-flex-column users-edit_form' title='Редактирование'>
        <input name="id" id="id" type="hidden" value="">
        <div class="material-input">
            <label class="material-input_label" for="edit-last_name">Фамилия</label>
            <input class="material-input_text" name="last_name" id="edit-last_name" data-mask="name" type="text" required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="edit-first_name">Имя</label>
            <input class="material-input_text" name="first_name" id="edit-first_name" data-mask="name" type="text" required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="edit-middle_name">Отчество</label>
            <input class="material-input_text" name="middle_name" id="edit-middle_name" data-mask="name" type="text" required/>
        </div>
        <div class="material-input">
            <label class="material-input_label" for="edit-invoice_num">Лицевой счет</label>
            <input class="material-input_text" name="invoice_num" id="edit-invoice_num"/>
        </div>

        <div class="material-input" data-view="4">
            <label for="edit-building_id" class="material-input_label"></label>
            <select id="edit-building_id" class="material-input_text" person="true" type="text" name="building_id">
                <option id="selected-building" value=""></option>
                @foreach ($buildings as $build)
                    <option value="{{ $build->id }}"> ул.{{ $build->street_name }}
                        {{ $build->building_number }}
                        @if ($build->apart_number)
                            {{ 'кв. ' }}{{ $build->apart_number }}
                        @endif
                    </option>
                @endforeach
            </select>
        </div>
        <button class="button uk-margin-large-top" data-mode="send" type="button">Записать</button>
    </form>
@stop