routes/web.php
<?php

Artisan::call('view:clear');

// Auth
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/', 'Auth\LoginController@index')->name('main');

// News
// $router->resource('news', 'NewsController')->middleware('admin');
// Route::post('news/remove', 'NewsController@remove')->middleware('admin');
// Route::get('news/{news}/edit','NewsController@edit')->name('news.edit');

// Contacts
Route::post('contacts/remove', 'ContactController@remove')->middleware('admin');
$router->resource('contacts', 'ContactController')->middleware('admin');

// Streets
$router->resource('streets', 'StreetController')->middleware('admin');

// Buildings
$router->resource('buildings', 'BuildingController')->middleware('admin');
Route::post('buildings/remove', 'BuildingController@remove')->middleware('admin');

// Users
Route::get('users/balance', 'UsersController@getBalance')->middleware('auth', 'admin_user');
Route::get('users/street/{street}', 'UsersController@street')->middleware('admin');
Route::post('users/remove', 'UsersController@remove')->middleware('admin');
Route::post('users/phone', 'UsersController@handlerConfirmationPhone')->middleware('auth');
Route::post('users/phone-confirm', 'UsersController@confirmPhone')->middleware('auth');
Route::post('users/email', 'UsersController@handlerConfirmationEmail');
Route::get('users/email-confirm/{token}', 'UsersController@confirmEmail')->name('users.email-confirm');
Route::post('users/unbind', 'UsersController@unbind')->middleware('admin');
$router->resource('users', 'UsersController')->middleware('admin');

// Autos
// Route::post('autos/remove', 'AutoController@remove')->middleware('auth', 'admin_user');
// Route::post('autos/change', 'AutoController@change')->middleware('auth', 'admin_user');
// $router->resource('autos', 'AutoController')->middleware('auth', 'admin_user');

// Guests
// Route::post('guests/remove', 'GuestController@remove')->middleware('auth', 'admin_user');
// Route::post('guests/change', 'GuestController@change')->middleware('auth', 'admin_user');
// $router->resource('guests', 'GuestController')->middleware('auth', 'admin_user');

// Cars
Route::post('cars/remove', 'CarController@remove')->middleware('auth', 'admin_user');
Route::post('cars/change', 'CarController@change')->middleware('auth', 'admin_user');
$router->resource('cars', 'CarController')->middleware('auth', 'admin_user');

// Peoples
Route::post('peoples/remove', 'PeopleController@remove')->middleware('auth', 'admin_user');
Route::post('peoples/change', 'PeopleController@change')->middleware('auth', 'admin_user');
$router->resource('peoples', 'PeopleController')->middleware('auth', 'admin_user');

// Profiles
$router->resource('profiles', 'ProfileController')->middleware('auth', 'user');
Route::get('profiles', 'ProfileController@index')->name('profiles.index')->middleware('auth', 'user');
Route::post('kins/remove', 'ProfileController@remove')->middleware('auth', 'user');

// Indications (on home page icons electricity and water)
Route::get('indications/month/{month}', 'IndicationController@month')->middleware('admin');
Route::post('indications/{indication}', 'IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications', 'IndicationController')->middleware('admin');

// Information
Route::get('informations/{sys_id}', 'InformationController@index')->middleware('auth');

// Indications
Route::get('indications/month/{month}','IndicationController@month')->middleware('admin');
Route::post('indications/{indication}','IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications','IndicationController')->middleware('admin');

// Polls
$router->resource('polls', 'PollController')->middleware('admin');
Route::post('polls/insert', 'PollController@insert');

// Additionals
Route::post('additionals/store', 'AdditionalController@store')->name('additionals.store');
Route::post('additionals/pay', 'AdditionalController@pay')->name('additional_pay');
Route::get('additionals/pdf', 'AdditionalController@makePdfAct');
Route::post('additionals/pay-unpaid', 'AdditionalController@payUnpaid');
Route::get('additionals/list', 'AdditionalController@lists');
Route::post('additionals/send/act', 'AdditionalController@sendAct')->name('additionals_send_act');
$router->resource('additionals', 'AdditionalController');

Auth::routes();
Route::post('password/change', 'UsersController@changePassword')->middleware('user');

// Access
Route::get('permitions', 'PermitionController@index')->name('permitions')->middleware('auth', 'admin_user');
Route::get('permitions/list', 'PermitionController@list')->name('permitions_list')->middleware('auth', 'admin_security');
Route::get('permitions/list/check', 'PermitionController@check');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth', 'common');

// Invoices
Route::group(['prefix' => 'invoices', 'middleware' => 'auth', 'middleware' => 'user'], function() {
    Route::get('/', 'InvoiceController@index');
    Route::get('period', 'InvoiceController@getAllByPeriod');
    Route::get('pdf', 'InvoiceController@showInPdf');
});

// Crons
Route::group(['prefix' => 'crons'], function() {
    Route::post('payments/confirm', 'CronController@confirmPayments'); 
    Route::post('users/add-counteragent-key', 'CronController@addCounteragentKey');
    Route::post('payments/mark-unpaid', 'CronController@markUnpaidPayments');
    Route::post('receipt/email', 'CronController@sentEmailReceiptPdf');
    Route::post('receipt/reset', 'CronController@resetReceipt');
    Route::post('cars/delete-expired-permition', 'CronController@deleteCarsWithExpiredPermition');
    // Route::get('test', 'CronController@test');
});

// Payments
Route::group(['prefix' => 'payments'], function() {
    Route::post('/', 'PaymentController@store')->middleware('auth', 'user');
    Route::post('handler', 'PaymentController@handler');
    // метод для тестов разной хуйни
    Route::get('cashbox', 'PaymentController@cashbox')->middleware('auth', 'user');
});

$router->resource('receipt', 'ReceiptController');

// Logs
Route::get('logs', 'LogController@index')->name('logs')->middleware('auth', 'admin');

// Route::get('streets','StreetController@index')->name('streets.index');

app/Http/Controllers/PermitionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Car;
use App\Models\People;
use App\Models\Profile;

class PermitionController extends Controller
{
    public function index()
    {
        $userRole = Auth::user()->role;
        $userId = Auth::user()->id;

        if ($userRole < 3) {
            $peoples = People::getAllUnPersonal();
            $cars = Car::getAllUnPersonal();
        } elseif ($userRole >= 3){
            $cars = Car::getAllByUser($userId);
            $peoples = People::getAllByUser($userId);
        }
        
        return view('permition.index', [
            'peoples' => $peoples,
            'cars' => $cars
        ]);
    }

    public function list()
    {
        $peoples = People::getActive();
        $cars = Car::getActive();
        
        $lastIds = collect([
            'people' => $peoples->first()->id,
            'car' => Car::orderBy('id', 'desc')->first()->id
        ]);

        return view('permition.list', [
            'peoples' => $peoples,
            'cars' => $cars,
            'lastIds' => $lastIds
        ]);
    }

    public function check(Request $request)
    {
        if ($this->existsNewPermitions($request)) {        
            return response()->json([
                'newPermitions' => true  
            ]);
        }

        return response()->json([
            'newPermitions' => false
        ]);
    }

    public function existsNewPermitions(Request $request)
    {
        $lastPeople = People::orderBy('id', 'desc')->first(); 
        $lastCar = Car::orderBy('id', 'desc')->first();

        $peopleId = (int) $request->people;
        $carId = (int) $request->car;

        if ($peopleId < $lastPeople->id || $carId < $lastCar->id) {
            return true;
        }

        return false;
    }
}

resources/views/permition/index.blade.php
@extends ('app')

@section ('content')
    <main class="uk-background-default uk-padding">
        <div class="uk-container uk-padding-remove uk-margin-top">
            <div class="uk-width-1-1">
                <div class="uk-text-lead">Временные пропуска</div>
            </div>

            <hr class="uk-divider-icon">

            <div class="uk-grid-small@s" uk-grid>
                <div class="uk-width-1-2@m uk-width-1-1@s">
                    <div class="uk-flex uk-flex-between uk-flex-middle">

                        <div class="uk-text-lead">
                            @if(count($peoples) != 0)
                                Пешеходы
                            @else
                                <span class="color-grey">Вы ещё не добавили
                                    <span class="color-gold"> пешеходов</span>
                                </span>
                            @endif
                        </div>
                        @if (Auth::user()->role != 4)
                            <button class="button button-icon button-fit add_people" form="peoples" data-mode="create">
                                <img src="/img/icon/admin/plus.svg"/>Добавить
                            </button>
                        @endif
                    </div>

                    @if(count($peoples) != 0)
                        <table class="uk-table table-permition" table="peoples">
                            <thead class="table-header">
                            <th>Действие</th>
                            <th>фИО</th>
                            <th>Действителен</th>
                            <th>Примечание</th>
                            @if (Auth::user()->role < 3)
                                <th>Создал</th>
                            @endif
                            <th></th>
                            </thead>
                            <tbody>
                            @foreach ($peoples as $people)
                                <tr class="table-item people_item" id="{{ $people->id }}">
                                    <td>
                                        @if (Auth::user()->role != 4)
                                            <div class="uk-flex">
                                                <button class="button-transparent button-icon" action="peoples"
                                                        data-mode="delete">
                                                    <img src="/img/icon/admin/street/delete.svg">
                                                </button>
                                                <button class="button-transparent button-icon" action="peoples"
                                                        data-mode="edit">
                                                    <img src="/img/icon/edit.svg">
                                                </button>
                                            </div>
                                        @endif
                                    </td>
                                    <td>
                                        <div>{{ $people->last_name }}</div>
                                        <div>{{ $people->first_name }}</div>
                                        <div>{{ $people->middle_name }}</div>
                                    </td>
                                    <td>
                                        @if ($people->personal != 1)
                                            {{ $people->close_date }}
                                            @if ($people->close_count >= 0)
                                                <span class="color-green"> ({{ $people->close_count }}д.)</span>
                                            @else
                                                <span class="color-red">(истёк)</span>
                                            @endif
                                        @endif
                                    </td>
                                    <td>
                                        <div>{{ $people->note }}</div>
                                    </td>
                                    @if (Auth::user()->role < 3)
                                        <td>
                                            <div>{{ $people->street_name }}<span>{{ $people->building_number }}</span>
                                            </div>
                                            <div>{{ $people->user_last_name }} {{ $people->user_first_name }} {{ $people->user_middle_name }}</div>
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <table class="uk-table table-permition table-blank" table="peoples">
                            <thead class="table-header">
                            <th>
                                <div class="table-blank__item"></div>
                            </th>
                            <th>
                                <div class="table-blank__item table-blank__item-m"></div>
                            </th>
                            </thead>
                            <tbody>
                                @for ($i = 1; $i < 4; $i++)
                                    <tr>
                                        <td>
                                            <div class="table-blank__item"></div>
                                        </td>
                                        <td>
                                            <div class="table-blank__item table-blank__item-m"></div>
                                        </td>
                                    </tr>
                                @endfor
                            </tbody>
                        </table>
                    @endif
                </div>

                <div class="uk-width-1-2@m uk-width-1-1@s">
                    <div class="uk-flex uk-flex-between uk-flex-middle">
                        <div class="uk-text-lead">
                            @if(count($cars) != 0)
                                Автомобили
                            @else
                                <span class="color-grey">Вы ещё не добавили
                                    <span class="color-gold"> автомобили</span>
                                </span>
                            @endif
                        </div>
                        @if (Auth::user()->role != 4)
                            <button class="button button-icon button-fit" form="cars" data-mode="create">
                                <img src="/img/icon/admin/plus.svg"/>Добавить
                            </button>
                        @endif
                    </div>

                    @if(count($cars) != 0)
                        <table class="uk-table table-permition" table="cars">
                            <thead class="table-header">
                            <th>Дейстивие</th>
                            <th>Автомобиль</th>
                            <th>Действителен</th>
                            <th>Примечание</th>
                            @if (Auth::user()->role < 3)
                                <th>Создал</th>
                            @endif
                            <th></th>
                            </thead>
                            <tbody>
                            @foreach($cars as $car)
                                <tr class="table-item auto_item" id="{{ $car->id }}">
                                    <td>
                                        @if (Auth::user()->role != 4)
                                            <div class="uk-flex">
                                                <button class="button-transparent button-icon" action="cars"
                                                        data-mode="delete">
                                                    <img src="/img/icon/admin/street/delete.svg"></button>

                                                <button class="button-transparent button-icon" action="cars"
                                                        data-mode="edit">
                                                    <img src="/img/icon/edit.svg"></button>
                                            </div>
                                        @endif
                                    </td>
                                    <td>
                                        {{ $car->number }}
                                        <div class="table-align-left car_name">{{ $car->model }}</div>
                                        <div class="table-align-left car_name">{{ $car->mark }}</div>
                                    </td>
                                    <td>
                                        @if ($car->personal != 1)
                                            {{ $car->close_date }}
                                            @if ($car->close_count >= 0)
                                                <span class="color-green"> ({{ $car->close_count }}д.)</span>
                                            @else
                                                <span class="color-red">(истёк)</span>
                                            @endif
                                        @endif
                                    </td>
                                    <td>{{ $car->note }}</td>
                                    @if (Auth::user()->role < 3)
                                        <td>
                                            <div>{{ $car->street_name }}<span>{{ $car->building_number }}</span></div>
                                            <div>{{ $car->last_name }} {{ $car->first_name }} {{ $car->middle_name }}</div>
                                        </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <table class="uk-table table-permition table-blank" table="cars">
                            <thead class="table-header">
                            <th>
                                <div class="table-blank__item table-blank__item-s"></div>
                            </th>
                            <th>
                                <div class="table-blank__item table-blank__item"></div>
                            </th>
                            <th>
                                <div class="table-blank__item table-blank__item-m"></div>
                            </th>
                            </thead>
                            <tbody>
                            @for ($i = 1; $i < 4; $i++)
                                <tr>
                                    <td>
                                        <div class="table-blank__item table-blank__item-s"></div>
                                    </td>
                                    <td>
                                        <div class="table-blank__item-m"></div>
                                        <div class="table-blank__item"></div>
                                    </td>
                                    <td>
                                        <div class="table-blank__item table-blank__item-m"></div>
                                    </td>
                                </tr>
                            @endfor
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </main>
    @include('permition.perform')
@stop

resources/views/permition/list.blade.php
@extends ('app')

@section ('content')
    <main class="uk-background-default uk-padding">
        <div class="uk-container uk-margin-top uk-padding-remove ">
            <div class="uk-width-1-1">
                <div class="uk-heading-primary">Пропуска</div>
            </div>
            <div class="uk-grid-small@s uk-margin-top" uk-grid>
                <div class="uk-width-1-1@">
                    <ul uk-tab uk-switcher>
                        <li class="uk-text-lead uk-active"><a href="#">Автомобили</a></li>
                        <li class="uk-text-lead"><a href="#">Гости</a></li>
                    </ul>
                    <ul class="uk-switcher uk-margin">
                        <li>
                            <div class="uk-overflow-auto">
                            <table class="uk-table uk-table-divider uk-table-hover uk-margin-top uk-margin-bottom display" id="car-list">
                                <thead>
                                <tr>
                                    <th>Номер</th>
                                    <th>Марка</th>
                                    <th>Модель</th>
                                    <th>Статус</th>
                                </tr>
                                </thead>
                            </table>
                            </div>
                        </li>
                        <li>
                            <div class="uk-overflow-auto">
                            <table class="uk-table uk-table-divider uk-table-hover uk-margin-top uk-margin-bottom" id="people-list">
                                <thead>
                                <tr>
                                    <th>Фамилия</th>
                                    <th>Имя</th>
                                    <th>Примечание</th>
                                    <th>Улица</th>
                                    <th>Адрес</th>
                                    <th>Статус</th>
                                </tr>
                                </thead>
                            </table>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
    <script>
        var cars = @php echo $cars; @endphp ;
        var peoples = @php echo $peoples; @endphp ;
        var lastIds = @php echo $lastIds; @endphp ;
        var car_list = [];
        var people_list = [];

        for (var i in cars) {
            switch (cars[i]['personal']) {
              case 1:
                cars[i]['personal'] = 'Житель';
                break;
              case 0:
                cars[i]['personal'] = 'Гость';
                break;
              case undefined:
                cars[i]['personal'] = 'Житель';
                break;
            }

            car_list.push([cars[i]['number'],
                            cars[i]['mark'],
                            cars[i]['model'],
                            cars[i]['personal']
                            ]);
        }

        for (var i in peoples) {
            switch (peoples[i]['personal']) {
              case 1:
                peoples[i]['personal'] = 'Житель';
                break;
              case 0:
                peoples[i]['personal'] = 'Гость';
                break;
              case undefined:
                peoples[i]['personal'] = 'Житель';
                break;
            }

            people_list.push([peoples[i]['last_name'],
                            peoples[i]['first_name'],
                            peoples[i]['note'],
                            peoples[i]['street_name'],
                            peoples[i]['building_number'],
                            peoples[i]['personal']
                            ]);
        }

        $("#car-list").DataTable({
            "dom": 'Bftrip',
            "data": car_list,
            "buttons": [
                {
                    text: 'Excel',
                    className: 'button button-default',
                    filename: 'Пропуска "КП Донской"',
                    extend: 'excel',
                    exportOptions: {
                        modifier: {
                            page: 'all'
                        }
                    }
                },],
            "language": {
                "lengthMenu": "Показать _MENU_ записей на странице",
                "zeroRecords": "Ничего не найдено",
                "info": "Страница _PAGE_ из _PAGES_",
                "infoEmpty": "Нет доступных записей",
                "search": "Поиск:",
                "paginate": {
                    "first":      "Первая",
                    "last":       "Последняя",
                    "next":       "Следующая",
                    "previous":   "Предыдущая"
                },
                "infoFiltered": "(Отфильтровано из _MAX_ событий)"
            },
        });

        $("#people-list").DataTable({
            "dom": 'Bftrip',
            "data": people_list,
            "buttons": [
                {
                    text: 'Excel',
                    className: 'button button-default',
                    filename: 'Пропуска "КП Донской"',
                    extend: 'excelHtml5',
                    exportOptions: {
                        modifier: {
                            page: 'all'
                        }
                    }
                },],
            "language": {
                "lengthMenu": "Показать _MENU_ записей на странице",
                "zeroRecords": "Ничего не найдено",
                "info": "Страница _PAGE_ из _PAGES_",
                "infoEmpty": "Нет доступных записей",
                "search": "Поиск:",
                "paginate": {
                    "first":      "Первая",
                    "last":       "Последняя",
                    "next":       "Следующая",
                    "previous":   "Предыдущая"
                },
                "infoFiltered": "(Отфильтровано из _MAX_ событий)"
            },
        });

        setInterval(function() {
            $.ajax({
                url: 'https://lk.kp-donskoy.ru/permitions/list/check',

                data:{
                    car: lastIds['car'],
                    people: lastIds['people'],
                },

                success: function(res){
                    if (res.newPermitions){
                        location.reload();
                    }
                },

                error: function(e) {
                    console.log('error', e);
                }
            })}, 50000);
    </script>
    <script src="/js/security.js?{{filemtime('../public/js/security.js')}}"></script>
@stop

resources/views/permition/perform.blade.php
<form action="{{ route('peoples.store') }}" class="hidden-form uk-padding uk-flex uk-flex-column peoples-edit_form" focus-input="first"
      title="Новый пропуск" table="peoples">
    {{ csrf_field() }}
    <input name="id" type="hidden" value=""/>
    <div class="material-input">
        <label class="material-input_label" for="last_name">Фамилия</label>
        <input class="material-input_text" name="last_name" id="last_name" data-input="capitalize" lang="ru" required type="text"/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="first_name">Имя</label>
        <input class="material-input_text" name="first_name" id="first_name" data-input="capitalize" lang="ru" required type="text"/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="middle_name">Отчество</label>
        <input class="material-input_text" name="middle_name" id="middle_name" data-input="capitalize" lang="ru" required type="text"/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="close_date">Срок действия</label>
        <input class="material-input_text" name="close_date" data-mask="permition" required/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="note">Примечание</label>
        <input class="material-input_text" name="note" id="note" lang="ru" type="text"/>
    </div>
    <input class="material-input_text" name="birthday" type="hidden" value="0000-00-00"/>
    <button class="uk-margin-large-top button" type="button" data-mode="send">Оформить</button>
</form>

<form action="{{ route('cars.store') }}" class="hidden-form uk-padding uk-flex uk-flex-column cars-edit_form" focus-input="first"
      title="Новый пропуск" table="cars">
    {{ csrf_field() }}
    <input name="id" type="hidden" value=""/>
    <input name="databaseId" type="hidden" value="4"/>

    <div class="number-template uk-grid-small uk-margin-medium-top" uk-grid>
        <div class="uk-width-auto">
            <select class="number-template__mask" name="number_mask">
              <option value="russian">RU</option>
              <option value="dpr">DPR</option>
              <option value="ukrainian">UA</option>
              <option value="armenian">AM</option>
            </select>
        </div>
        <div class="uk-width-expand">
            <div class="number-template__input material-input">
                <label class="material-input_label" for="number">Номер машины</label>
                <!-- data-mask="length_limit" -->
                <input class="material-input_text number_car" name="number" id="number" error-place="number-template" data-input="uppercase" data-mask="russian" nospace required/>
            </div>
        </div>
        <div class="uk-width-auto">
            <div class="number-template__item" template="russian" default="A000AA00" style="display: block;">A000AA00</div>
            <div class="number-template__item" template="dpr" default="A000AA">A000AA</div>
            <div class="number-template__item" template="ukrainian" default="AA0000AA">AA0000AA</div>
            <div class="number-template__item" template="armenian" default="00AA000">00AA000</div>
        </div>
    </div>

    <div class="material-input">
        <label class="material-input_label" for="mark">Марка</label>
        <input class="material-input_text" name="mark" id="mark" data-input="uppercase" nospace required type="text"/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="model">Модель</label>
        <input class="material-input_text" name="model" id="model" data-input="uppercase" nospace type="text"/>
    </div>
    <div class="material-input">
        <label class="material-input_label" for="close_date">Срок действия</label>
        <input class="material-input_text" name="close_date" data-mask="permition" required/>
    </div>
        <div class="material-input">
        <label class="material-input_label" for="note">Примечание</label>
        <input class="material-input_text" name="note" id="note" lang="ru" type="text"/>
    </div>
    <button class="uk-margin-large-top button" type="button" data-mode="send">Оформить</button>
</form>