routes/web.php
<?php

Artisan::call('view:clear');

// Auth
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/', 'Auth\LoginController@index')->name('main');

// News
// $router->resource('news', 'NewsController')->middleware('admin');
// Route::post('news/remove', 'NewsController@remove')->middleware('admin');
// Route::get('news/{news}/edit','NewsController@edit')->name('news.edit');

// Contacts
Route::post('contacts/remove', 'ContactController@remove')->middleware('admin');
$router->resource('contacts', 'ContactController')->middleware('admin');

// Streets
$router->resource('streets', 'StreetController')->middleware('admin');

// Buildings
$router->resource('buildings', 'BuildingController')->middleware('admin');
Route::post('buildings/remove', 'BuildingController@remove')->middleware('admin');

// Users
Route::get('users/balance', 'UsersController@getBalance')->middleware('auth', 'admin_user');
Route::get('users/street/{street}', 'UsersController@street')->middleware('admin');
Route::post('users/remove', 'UsersController@remove')->middleware('admin');
Route::post('users/phone', 'UsersController@handlerConfirmationPhone')->middleware('auth');
Route::post('users/phone-confirm', 'UsersController@confirmPhone')->middleware('auth');
Route::post('users/email', 'UsersController@handlerConfirmationEmail');
Route::get('users/email-confirm/{token}', 'UsersController@confirmEmail')->name('users.email-confirm');
Route::post('users/unbind', 'UsersController@unbind')->middleware('admin');
$router->resource('users', 'UsersController')->middleware('admin');

// Autos
// Route::post('autos/remove', 'AutoController@remove')->middleware('auth', 'admin_user');
// Route::post('autos/change', 'AutoController@change')->middleware('auth', 'admin_user');
// $router->resource('autos', 'AutoController')->middleware('auth', 'admin_user');

// Guests
// Route::post('guests/remove', 'GuestController@remove')->middleware('auth', 'admin_user');
// Route::post('guests/change', 'GuestController@change')->middleware('auth', 'admin_user');
// $router->resource('guests', 'GuestController')->middleware('auth', 'admin_user');

// Cars
Route::post('cars/remove', 'CarController@remove')->middleware('auth', 'admin_user');
Route::post('cars/change', 'CarController@change')->middleware('auth', 'admin_user');
$router->resource('cars', 'CarController')->middleware('auth', 'admin_user');

// Peoples
Route::post('peoples/remove', 'PeopleController@remove')->middleware('auth', 'admin_user');
Route::post('peoples/change', 'PeopleController@change')->middleware('auth', 'admin_user');
$router->resource('peoples', 'PeopleController')->middleware('auth', 'admin_user');

// Profiles
$router->resource('profiles', 'ProfileController')->middleware('auth', 'user');
Route::get('profiles', 'ProfileController@index')->name('profiles.index')->middleware('auth', 'user');
Route::post('kins/remove', 'ProfileController@remove')->middleware('auth', 'user');

// Indications (on home page icons electricity and water)
Route::get('indications/month/{month}', 'IndicationController@month')->middleware('admin');
Route::post('indications/{indication}', 'IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications', 'IndicationController')->middleware('admin');

// Information
Route::get('informations/{sys_id}', 'InformationController@index')->middleware('auth');

// Indications
Route::get('indications/month/{month}','IndicationController@month')->middleware('admin');
Route::post('indications/{indication}','IndicationController@update')->name('indications.update')->middleware('admin');
$router->resource('indications','IndicationController')->middleware('admin');

// Polls
$router->resource('polls', 'PollController')->middleware('admin');
Route::post('polls/insert', 'PollController@insert');

// Additionals
Route::post('additionals/store', 'AdditionalController@store')->name('additionals.store');
Route::post('additionals/pay', 'AdditionalController@pay')->name('additional_pay');
Route::get('additionals/pdf', 'AdditionalController@makePdfAct');
Route::post('additionals/pay-unpaid', 'AdditionalController@payUnpaid');
Route::get('additionals/list', 'AdditionalController@lists');
Route::post('additionals/send/act', 'AdditionalController@sendAct')->name('additionals_send_act');
$router->resource('additionals', 'AdditionalController');

Auth::routes();
Route::post('password/change', 'UsersController@changePassword')->middleware('user');

// Access
Route::get('permitions', 'PermitionController@index')->name('permitions')->middleware('auth', 'admin_user');
Route::get('permitions/list', 'PermitionController@list')->name('permitions_list')->middleware('auth', 'admin_security');
Route::get('permitions/list/check', 'PermitionController@check');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth', 'common');

// Invoices
Route::group(['prefix' => 'invoices', 'middleware' => 'auth', 'middleware' => 'user'], function() {
    Route::get('/', 'InvoiceController@index');
    Route::get('period', 'InvoiceController@getAllByPeriod');
    Route::get('pdf', 'InvoiceController@showInPdf');
});

// Crons
Route::group(['prefix' => 'crons'], function() {
    Route::post('payments/confirm', 'CronController@confirmPayments'); 
    Route::post('users/add-counteragent-key', 'CronController@addCounteragentKey');
    Route::post('payments/mark-unpaid', 'CronController@markUnpaidPayments');
    Route::post('receipt/email', 'CronController@sentEmailReceiptPdf');
    Route::post('receipt/reset', 'CronController@resetReceipt');
    Route::post('cars/delete-expired-permition', 'CronController@deleteCarsWithExpiredPermition');
    // Route::get('test', 'CronController@test');
});

// Payments
Route::group(['prefix' => 'payments'], function() {
    Route::post('/', 'PaymentController@store')->middleware('auth', 'user');
    Route::post('handler', 'PaymentController@handler');
    // метод для тестов разной хуйни
    Route::get('cashbox', 'PaymentController@cashbox')->middleware('auth', 'user');
});

$router->resource('receipt', 'ReceiptController');

// Logs
Route::get('logs', 'LogController@index')->name('logs')->middleware('auth', 'admin');

// Route::get('streets','StreetController@index')->name('streets.index');

resources/views/admin/index.blade.php
@extends ('app')


@section ('content')
    <main class="uk-background-default  uk-padding">
        <div class="uk-container uk-padding-remove uk-margin-top">
            <div class="uk-width-1-1 uk-text-lead uk-margin-bottom">Главная</div>
            <div class="" uk-grid>
                <div class="uk-width-1-3@m uk-width-1-1@s street-container">
                    <ul class="street-list uk-list">
                        @foreach ($streets as $street)
                            <a href="{{ route("buildings.index",['street'=>$street->id]) }}">
                                <li class="street-list_item @if(isset($active_street) and $street->id == $active_street) active @endif "
                                    id="{{ $street->id }}" map_id="{{ $street->map_id }}">
                                    {{ $street->name }}
                                </li>
                            </a>
                        @endforeach
                    </ul>
                    <div class="button-group">
                        <button class="button button-icon" data-mode="create">
                            <img src="img/icon/admin/plus.svg"/>Добавить дом
                        </button>
                        <button class="button button-transparent button-icon" data-mode="create-street">Новая улица
                        </button>
                    </div>
                </div>
                <div class="uk-width-2-3@m uk-width-1-1@s uk-padding uk-padding-remove-top uk-padding-remove-right uk-overflow-auto table-container">
                    <table class="uk-table uk-table-divider uk-table-hover table-border-left" table="building">
                        <thead class="table-header">
                        <th>Дом</th>
                        {{--<th class="table-header__width-30">Характеристики</th>--}}
                        <th>Владелец</th>
                        <th></th>
                        </thead>
                        <tbody>
                        @foreach($buildings as $building)

                            <tr class="table_item" id="{{ $building->id }}">
                                <td>
                                    <div>
                                        @if ( $building->type == 'townhouse')
                                            {{ 'Таунхаус' }}
                                        @elseif ( $building->type == 'town')
                                            {{ 'Коттедж' }}
                                        @elseif ( $building->type == 'roof')
                                            {{ 'Многоэтажный дом' }}
                                        @endif

                                        @if ( $building->apart_type )
                                            ({{ $building->apart_type }})
                                        @endif
                                    </div>
                                    <div>ул.{{ $building->street_name }}, {{ $building->building_number }}
                                        @if ($building->apart_number)
                                                @if($building->floor)
                                                , этаж: {{ $building->floor }},
                                                @endif
                                             кв. {{ $building->apart_number }}
                                        @endif
                                    </div>
                                </td>

                                {{--
                            <td>
                                <div>
                                    {{ 'Площадь: ' }}{{ $building->area }}
                                    @if ( $building->space_area )
                                        {{ 'Этажей: ' }}{{ $building->floor }}
                                        <div>{{ 'Участок: ' }}{{ $building->space_area }}</div>
                                    @endif
                                </div>
                            </td>
                                --}}

                                <td>
                                    @if ( $building->last_name )
                                        <span>{{ $building->last_name }} {{ $building->first_name }} {{ $building->middle_name }}</span>
                                    @else
                                        <span></span>
                                    @endif
                                </td>

                                <td>
                                    <div class="button-group">
                                        <button class="button button-transparent button-icon" data-mode="edit"><img
                                                    src="img/icon/admin/street/edit.svg"></button>
                                        <button class="button button-transparent button-icon" data-mode="delete"><img
                                                    src="img/icon/admin/street/delete.svg"></button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $buildings->appends(['street'=>$active_street])->links() }}
                </div>

                {!! Form::open(['route'=>'streets.store','class'=>'hidden-form uk-padding uk-flex uk-flex-column form_street', 'title'=>'Новая улица']) !!}
                <div class="material-input">
                    <label class="material-input_label" for="street_name">Название улицы</label>
                    <input class="material-input_text" name="street_name" id="street_name"/>
                </div>
                <button data-mode="send" type="button" class="button uk-margin-large-top">Добавить</button>
                {!! Form::close() !!}


                {!! Form::open(['route'=>'buildings.store','class'=>'hidden-form uk-padding uk-flex uk-flex-column buildings-edit_form', 'title'=>'Новый дом']) !!}
                <input type="hidden" name="id" value="" id="id">

                <div class="material-input">
                    <label class="material-input_label" for="type">Тип строения</label>
                    <select class="material-input_text" id="type" name="type" onchange="showLines(this.value)">
                        <option value="roof">Многоэтажный дом</option>
                        <option value="townhouse">Таунхаус</option>
                        <option selected value="town">Коттедж</option>
                    </select>
                </div>

                <div class="material-input" data-visible="roof">
                    <label class="material-input_label" for="apart_type">Тип квартиры</label>
                    <select class="material-input_text" id="apart_type" data-visible="roof" name="apart_type">
                        <option value="" selected></option>
                        <option value="studio">Студия</option>
                        <option value="1th">1-комнатная</option>
                        <option value="2th">2x-комнатная</option>
                        <option value="3th">3x-комнатная</option>
                        <option value="4th">4x-комнатная</option>
                    </select>
                </div>

                <div class="material-input">
                    <label class="material-input_label" for="building_number">Номер дома</label>
                    <input class="material-input_text" maxlength="7" name="building_number" id="building_number"/>
                </div>
                <div class="material-input" data-visible="roof">
                    <label class="material-input_label" for="floor">Этаж</label>
                    <input class="material-input_text" data-visible="roof" name="floor" data-input="floor" id="floor"/>
                </div>
                <div class="material-input" data-visible="roof,townhouse">
                    <label class="material-input_label" for="apart_number">Номер квартиры</label>
                    <input class="material-input_text" type="number" data-visible="roof,townhouse" name="apart_number" min="1"
                           max="150" step="1" id="apart_number"/>
                </div>

                <button type="button" data-mode="send"  class="button uk-margin-large-top">Записать</button>
                {!! Form::close() !!}

            </div>
        </div>
    </main>
@stop

resources/views/admin/topbar.blade.php
@section('topbar')
    <topbar class="tool_panel uk-position-fixed uk-flex uk-full-width uk-flex-center uk-position-z-index">

        @php
        $menu = array(
            "Дома" => "buildings",
            "Услуги" => "additionals",
            "Пользователи" => "users",
            "Пропуска" => 'permitions',
            //"Показания" => 'indications',
            "События" => 'events',
        );
        @endphp

        @foreach ($menu as $title=>$url)
            @php
                $class = strpos($_SERVER["REQUEST_URI"], $url) !== false ? " active" : "";
            @endphp
            @if ($title == 'Пропуска')
                <span class="nav_item {{ $class }}">
                    <a href="{{ $url }}">{{ $title }}</a>
                    <div uk-dropdown class="uk-padding-small">
                        <a href="{{ $url }}/list">Все пропуска</a>
                    </div>
                </span>
            @else
                <span class="nav_item {{ $class }}"><a href="/{{ $url }}" pointer="{{ $url }}">{{ $title }}</a></span>
            @endif
        @endforeach
    </topbar>
@stop